server:
  port: 8000

spring:
  profiles:
    active: test
    include: feign
  application:
    name: service-order
  cloud:
    nacos:
      server-addr: 119.3.229.33:8848
      config:
        import-check:
          enabled: false
        namespace: ${spring.profiles.active:public}
        group: order
logging:
  level:
    com.atguigu.order.feign: debug

---
spring:
  config:
    import:
      - nacos:common.properties
      - nacos:database.properties
    activate:
      on-profile: dev
---
spring:
  config:
    import:
      - nacos:common.properties
      - nacos:database.properties
    activate:
      on-profile: test
---
spring:
  config:
    import:
      - nacos:common.properties
      - nacos:database.properties
    activate:
      on-profile: prod